test:
  script:
  - apt-get update -qy
  - apt-get install -qy --no-install-recommends python3-mutagen python3-gi-cairo gir1.2-poppler-0.18 gir1.2-gdkpixbuf-2.0 libimage-exiftool-perl
  - python3 -m unittest discover -v
